### ISSUE TITLE
How to obtain structure feature?

### ISSUE THREAD

**Issue by HUSTLyn** [cambridgeltl/eva#1]

**Comment by HUSTLyn** [comment]
Hi~
I notice that there is a file named  dwy15k_norm_sf_vec.npy that stores the structure features of the KGs. If I understand correctly, The vectors in this file are used to initialize the structure features.
I would like to know how this file was obtained?
Thanks~

**Comment by hardyqr** [comment]
Hi!

`dwy15k_norm_sf_vec.npy` stores features produced using the entity names ("sf" means surface form). They are computed using fasttext (when there are multiple words in the entity name, mean pooling is used). 

For embedding KG structure, GCN is used and the feature vectors are learned online instead of precomputed.

Hope this helps.

**Comment by HUSTLyn** [comment]
> Hi!
> 
> `dwy15k_norm_sf_vec.npy` stores features produced using the entity names ("sf" means surface form). They are computed using fasttext (when there are multiple words in the entity name, mean pooling is used).
> 
> For embedding KG structure, GCN is used and the feature vectors are learned online instead of precomputed.
> 
> Hope this helps.

Thank you for your patience!
